export const teamMembers = [
    {
        id: '1',
        image: '/images/team/dragosBacitea.jpeg',
        title: 'Founder of Network 3.0 & A-NFT',
        name: 'Dragoș Bacîtea',
        url: 'https://www.linkedin.com/in/dbacitea/',
        easterEgg: '/images/easterEgg/dragos-star-wars.png',
    },
    {
        id: '2',
        image: '/images/team/lucianBalulescu.jpeg',
        title: 'PR & Strategy Leader',
        name: 'Lucian Bălulescu',
        url: 'https://www.linkedin.com/in/luciancb/',
        easterEgg: '/images/easterEgg/lucian-easter-egg.png',
    },
    {
        id: '3',
        image: '/images/team/andreiBacitea.jpeg',
        title: 'Markting & Growth Hacking Specialist',
        name: 'Andrei Bacîtea',
        url: 'https://www.linkedin.com/in/andrei-bacitea-230376109/',
        easterEgg: '/images/easterEgg/andrei-easter-egg.png',
    },
    {
        id: '4',
        image: '/images/team/silviuGherman.png',
        title: 'Lead Developer',
        name: 'Silviu Gherman',
        url: 'https://www.linkedin.com/in/silviu-gherman/',
        easterEgg: '/images/easterEgg/silviu-easter-egg.png',
    },
    {
        id: '5',
        image: '/images/team/cristinaBoanta.jpeg',
        title: 'Frontend Developer',
        name: 'Frontend Developer',
        url: 'https://www.linkedin.com/in/cristina-boanta/',
        easterEgg: '/images/easterEgg/cristina-easter-egg.png',
    },
    {
        id: '6',
        image: '/images/team/bogdanTogoe.jpeg',
        title: 'Backend Developer',
        name: 'Bogdan Togoe',
        url: 'https://www.linkedin.com/in/bogdan-togoe-81441324a/',
        easterEgg: '/images/easterEgg/bogdan-easter-egg.png',
    },
    {
        id: '7',
        image: '/images/team/cristiApostol.jpeg',
        title: 'Backend Developer',
        name: 'Cristian Apostol',
        url: 'https://www.linkedin.com/',
        easterEgg: '/images/easterEgg/cristi-easter-egg.png',
    },
    {
        id: '8',
        image: '/images/team/arinaRomarniuc.jpeg',
        title: 'Frontend Developer',
        name: 'Arina Romarniuc',
        url: 'https://www.linkedin.com/',
        easterEgg: '/images/easterEgg/arina-easter-egg.png',
    },
    {
        id: '9',
        image: '/images/team/lucaStrinu.jpeg',
        title: 'Marketing Specialist',
        name: 'Luca Strinu',
        url: 'https://www.linkedin.com/',
        easterEgg: '/images/easterEgg/luca-easter-egg.png',
    },
];

export const collaborators = [
    {
        id: '1',
        image: '/images/collaborators/ianScarffe.png',
        title: 'Business Advisor',
        name: 'Ian Scarfe',
        url: 'https://www.linkedin.com/in/ianscarffe/',
        easterEgg: null,
    },
];
